// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlc

import (
	"context"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO event (payload) VALUES ($1)
`

func (q *Queries) InsertEvent(ctx context.Context, payload []byte) error {
	_, err := q.db.Exec(ctx, insertEvent, payload)
	return err
}
