services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: go
      POSTGRES_PASSWORD: go
      POSTGRES_DB: go
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
